config/routes.rb
Rails.application.routes.draw do

  get 'twitter/tweet'

  get 'tweet/tweet'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'us_relationships/create'

  get 'us_relationships/destroy'

  root 'top#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  resources :stations, only: [:index,:show] do
    resources :station_comments
  end
  
  resources :routes, only: [:index,:show] do
    resources :route_comments
  end
  
  resources :prefectures, only: [:index,:show] do
    resources :prefecture_comments
  end
  
  resources :us_relationships, only: [:create, :destroy]
  
  resources :users, only: [:show]
  

end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
    has_many :stations
    
    has_many :complete_prefectures
    has_many :user_id, :through => :complete_prefectures
    
    has_many :prefecture_comments, dependent: :destroy
    
    has_many :pr_relationships
    has_many :routes, :through => :pr_relationships
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  def index
    
    # http://nekorails.hatenablog.com/entry/2017/05/31/173925#第2章-シンプルモードで検索する
    
    if params[:q] != nil
      params[:q]['name_cont_all'] = params[:q]['name_cont_all'].split(/[\p{blank}\s]+/)
      @search = Prefecture.ransack(params[:q]) # この行を追加
      @prefectures = @search.result #この行を修正
    else
      @search = Prefecture.ransack(params[:q]) # この行を追加
      @prefectures = @search.result #この行を修正
    end
    @prefectures=@prefectures.sort{|a,b| a.id<=>b.id}
  end

  def show
    @prefecture=Prefecture.find(params[:id])
    @stations=@prefecture.stations.sort{|a,b| a.id<=>b.id}
    @routes=@prefecture.routes.sort{|a,b| a.id<=>b.id}
    @prefecture_comment=@prefecture.prefecture_comments.build
    @prefecture_comments=@prefecture.prefecture_comments
  end
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/views/prefectures/index.html.erb
<h1>都道府県一覧</h1>
<div class="row">
    <div class="form-group">
        <%= search_form_for @search, url: prefectures_path do |f| %>
            
            <div class="col-xs-10">
                <%= f.search_field :name_cont_all ,class: "form-control" ,id: "inputDefault" %>
            </div>
            <div class="col-xs-2">
                <%= f.submit '検索する' , class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>
<div class="bs-component">
    <table class="table table-striped table-hover ">
        <tbody>
            <% @prefectures.each do |prefecture| %>
                <tr>
                    <td>
                        <%= link_to prefecture_path(prefecture.id) do %>
                            <%= prefecture.name %>(<%= prefecture.number %>駅)
                        <% end %>
                        <% if user_signed_in? %>[<%= current_user.complete_prefectures.find_by(prefecture_id: prefecture.id).number %>/<%= prefecture.number %>] <% if current_user.complete_prefectures.find_by(prefecture_id: prefecture.id).complete %><span class="label label-primary">Complete!</span><% end %><% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/prefectures/show.html.erb
<div class="container">
    <div class="container-child col-md-12 col-sm-12 col-xs-12 ">
<h1><%= @prefecture.name %>(<%= @prefecture.number %>駅)<% if user_signed_in? %>[<%= current_user.complete_prefectures.find_by(prefecture_id: @prefecture.id).number %>/<%= @prefecture.number %>] <% if current_user.complete_prefectures.find_by(prefecture_id: @prefecture.id).complete %><span class="label label-primary">Complete!</span><% end %><% end %></h1>
</div>
</div>


<div class="container-child col-md-4 col-sm-12 col-xs-12 ">
        <div class="bs-component">
            <h4>路線一覧</h4>
            <table class="table table-striped table-hover ">
                <tbody>
<% @routes.each do |route| %>
    <tr>
                            <td>
        <% if route.active %>
            <%= link_to route_path(route.id) do %>
                <%= route.name %>
            <% end %>
        <% else %>
            <%= link_to route_path(route.id) do %>
                <%= route.name %><廃路線>
            <% end %>
        <% end %>
    </td>
                        </tr>
<% end %>
</tbody>
            </table>
        </div>
</div>

 <div class="container-child col-md-4 col-sm-12 col-xs-12 ">
        <div class="bs-component">
            <h4>駅一覧</h4>
            <table class="table table-striped table-hover ">
                <tbody>
<% @stations.each do |station| %>
    <tr>
                            <td>
        <% if station.active %>
            <%= link_to station_path(station.id) do %>
                <%= station.name %>
            <% end %>
            <% if user_signed_in? %>
                <%= render 'layouts/access_form',station: station %>
            <% end %>
        <% else %>
            <%= link_to station_path(station.id) do %>
                <%= station.name %><廃駅>
            <% end %>
            <% if user_signed_in? %>
                <%= render 'layouts/access_form',station: station  %>
            <% end %>
        <% end %>
    </td>
                        </tr>
<% end %>
</tbody>
            </table>
        </div>
</div>

<div class="container-child col-md-4 col-sm-12 col-xs-12 ">
<p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'layouts/comments_index', locals: { comments: @prefecture_comments, parent: @prefecture } %>
    </div>
    <% if user_signed_in? %>
    <%= render partial: 'layouts/comments_form', locals: { comment: @prefecture_comment, parent: @prefecture } %>
<% end %>
</div></div>