config/routes.rb
Rails.application.routes.draw do

  get 'twitter/tweet'

  get 'tweet/tweet'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'us_relationships/create'

  get 'us_relationships/destroy'

  root 'top#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  resources :stations, only: [:index,:show] do
    resources :station_comments
  end
  
  resources :routes, only: [:index,:show] do
    resources :route_comments
  end
  
  resources :prefectures, only: [:index,:show] do
    resources :prefecture_comments
  end
  
  resources :us_relationships, only: [:create, :destroy]
  
  resources :users, only: [:show]
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/complete_route.rb
class CompleteRoute < ActiveRecord::Base
    belongs_to :user
    belongs_to :route
end

app/models/pr_relationship.rb
class PrRelationship < ActiveRecord::Base
    belongs_to :prefecture
    belongs_to :route
end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
    has_many :stations
    
    has_many :complete_prefectures
    has_many :user_id, :through => :complete_prefectures
    
    has_many :prefecture_comments, dependent: :destroy
    
    has_many :pr_relationships
    has_many :routes, :through => :pr_relationships
end

app/models/prefecture_comment.rb
class PrefectureComment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  belongs_to :prefecture
end

app/models/route.rb
class Route < ActiveRecord::Base
    has_many :rs_relationships
    has_many :stations, :through => :rs_relationships
    
    has_many :complete_routes
    has_many :users, :through => :complete_routes
    
    has_many :route_comments, dependent: :destroy
    
    has_many :pr_relationships
    has_many :prefectures, :through => :pr_relationships
end

app/models/route_comment.rb
class RouteComment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  belongs_to :route
end

app/models/rs_relationship.rb
class RsRelationship < ActiveRecord::Base
    belongs_to :station
    belongs_to :route
end

app/models/station.rb
class Station < ActiveRecord::Base
    belongs_to :prefecture
    has_many :rs_relationships
    has_many :routes, :through => :rs_relationships
    
    has_many :us_relationships
    has_many :users, :through => :us_relationships
    
    has_many :station_comments, dependent: :destroy
end

app/models/station_comment.rb
class StationComment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  belongs_to :station
end

app/models/us_relationship.rb
class UsRelationship < ActiveRecord::Base
    belongs_to :user
    belongs_to :station
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  mount_uploader :avatar, AvatarUploader #deviseの設定配下に追記
  
  has_many :us_relationships, dependent: :destroy
  has_many :stations, :through => :us_relationships
         
  has_many :complete_prefectures, dependent: :destroy
  has_many :prefectures, :through => :complete_prefectures
  
  has_many :complete_routes, dependent: :destroy
  has_many :routes, :through => :complete_routes
  
  has_many :station_comments, dependent: :destroy
  has_many :route_comments, dependent: :destroy
  has_many :prefecture_comments, dependent: :destroy
  
   # 暗号化
  def self.encrypt(password)
    crypt = ActiveSupport::MessageEncryptor.new(ENV["SECURE"], ENV["CIPHER"])
    crypt.encrypt_and_sign(password)
  end

  # 復号化
  def self.decrypt(password)
    crypt = ActiveSupport::MessageEncryptor.new(ENV["SECURE"], ENV["CIPHER"])
    crypt.decrypt_and_verify(password)
  end

  
  
  def self.create_unique_string
    SecureRandom.uuid
  end       
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          token:    auth.credentials.token,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.token=encrypt(user.token)
      #user.skip_confirmation!
      user.save(validate: false)
      Prefecture.all.each do |prefecture|
        user.complete_prefectures.build(prefecture_id: prefecture.id).save
      end
      Route.all.each do |route|
        user.complete_routes.build(route_id: route.id).save
      end
    end
    user
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.name,##S
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          token:    auth.credentials.token,
          secret:   auth.credentials.secret,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.token=encrypt(user.token)
      user.secret=encrypt(user.secret)
      user.save
      Prefecture.all.each do |prefecture|
        user.complete_prefectures.build(prefecture_id: prefecture.id).save
      end
      Route.all.each do |route|
        user.complete_routes.build(route_id: route.id).save
      end
    end
    user
  end
  
  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
  
  def access!(station)
    us_relationships.create!(station_id: station.id)
  end
  
  def accessing?(station)
    us_relationships.find_by(station_id: station.id)
  end
  
  def unaccess!(station)
    us_relationships.find_by(station_id: station.id).destroy
  end
  
  
 
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def profile_img(user)
      return image_tag(user.avatar, alt: user.name) if user.avatar?

      unless user.provider.blank?
        img_url = user.image_url
      else
        img_url = 'no_image.png'
      end
      image_tag(img_url, alt: user.name)
    end
    
    def new_profile_img(user,imgsize)
        return image_tag(user.avatar, alt: user.name, size: imgsize) if user.avatar?

        unless user.provider.blank?
            img_url = user.image_url
        else
            img_url = 'no_image.png'
        end
        image_tag(img_url, alt: user.name, size: imgsize)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
    def route_count(route)
        stations=route.stations
        count=0
        stations.each do |station|
            if current_user.stations.find_by(station_id: station.id)!=nil
               count=count+1
            end
       end
       return count
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_access_form.html.erb
<div id="access_form_<%= station.id %>">
  <% unless current_user.accessing?(station) %>
    <%= form_for(current_user.us_relationships.build(station_id: station.id), remote: true) do |f| %>
      <%= f.hidden_field :station_id %>
      <%= f.submit "未アクセス", class: "btn btn-primary btn-xs" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.us_relationships.find_by(station_id: station.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "アクセス済", class: "btn btn-primary btn-xs" %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_comments_form.html.erb
<%= form_for([parent,comment],remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= comment.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if parent.class.name=="Station" %><%= f.hidden_field :station_id %><% end %>
  <% if parent.class.name=="Route" %><%= f.hidden_field :route_id %><% end %>
  <% if parent.class.name=="Prefecture" %><%= f.hidden_field :prefecture_id %><% end %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_comments_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= new_profile_img(comment.user,"16x16") if profile_img(comment.user) %><%= comment.user.name %>さんがコメントしました。</p>
        
        
        <p class="left"><%= comment.content %></p>
        <% if user_signed_in? %>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <% if parent.class.name=="Station" %>
                <%= link_to '編集', edit_station_station_comment_path(parent, comment), class: "fa fa-pencil-square-o fa-lg" %>
                <%= link_to '削除', station_station_comment_path(parent, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
            <% end %>
            <% if parent.class.name=="Route" %>
                <%= link_to '編集', edit_route_route_comment_path(parent, comment), class: "fa fa-pencil-square-o fa-lg" %>
                <%= link_to '削除', route_route_comment_path(parent, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
            <% end %>
            <% if parent.class.name=="Prefecture" %>
                <%= link_to '編集', edit_prefecture_prefecture_comment_path(parent, comment), class: "fa fa-pencil-square-o fa-lg" %>
                <%= link_to '削除', prefecture_prefecture_comment_path(parent, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
            <% end %>
          </p>
        <% end %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_station_index.html.erb
<div class="bs-component">
            <table class="table table-striped table-hover ">
                <tbody>
<% stations.each do |station| %>
    <tr>
                            <td>
        <% if station.active %>
            <%= link_to station_path(station.id) do %>
                <%= station.name %>(<%= station.prefecture.name %>)
            <% end %>
            <% if user_signed_in? %>
                <%= render 'layouts/access_form',station: station %>
            <% end %>
        <% else %>
            <%= link_to station_path(station.id) do %>
                <%= station.name %><廃駅>(<%= station.prefecture.name %>)
            <% end %>
            <% if user_signed_in? %>
                <%= render 'layouts/access_form',station: station  %>
            <% end %>
        <% end %>
    </td>
                        </tr>
<% end %>
</tbody>
            </table>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>駅レコ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:creator" content="@kanineshi">
  <meta property="og:url" content="https://station-record.herokuapp.com/" />
  <meta property="og:title" content="駅レコ" />
  <meta property="og:description" content="某位置情報ゲーの便利ツール" />
  <meta property="og:image" content="assets/images/no_image.png" />
  
</head>
<body>

<header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "駅レコ", root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %><% if current_user.provider=="twitter" %><li><%= link_to "つぶやく", twitter_tweet_path %></li><% end %><% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">メニュー<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to '都道府県一覧',prefectures_path %></li>
                <li><%= link_to '路線一覧',routes_path %></li>
                <li><%= link_to '駅一覧',stations_path %></li>
              </ul>
            </li>
            <% if user_signed_in? %>
              <li><%= link_to 'マイページ', user_path(current_user.id) %></li>
              <li><%= link_to "ログアウト",destroy_user_session_path,method: :delete %></li>
            <% else %>
              <li><%= link_to "ログイン",new_user_session_path %></li>
              <li><%= link_to "サインアップ",new_user_registration_path %></li>
            <% end %> 
            
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>
  

<div class="container">
  <section class="main-header">
    <% if alert  %>
      <div class="row">
        <div class="col-lg-12">
          <div class="bs-component">
            <div class="alert alert-dismissible alert-warning">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <p><%= alert %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% if notice %>
      <div class="row">
        <div class="col-lg-12">
          <div class="bs-component">
            <div class="alert alert-dismissible  alert-success">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <p><%= notice %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</section>
<%= yield %>

</div>
<footer>
  <div>
    <p>作成者：@kanineshi</p>
  </div>
</footer>

</body>
</html>